#!/usr/bin/env python3
"""
Generate TownBase subclasses from a list of town names.

Usage:
    python generate_towns.py towns.txt ./towns --country Kenya --dataset kenya --country-code KE

towns.txt example:

Nairobi
Mombasa
Kisumu
Nakuru
Eldoret
...

Requirements:
    pip install requests
"""

from pathlib import Path
import argparse
import re
import time
import requests

USER_AGENT = "HiMapTownGenerator/1.0 (contact: your-email@example.com)"

DEFAULT_EXTENTS = {
    "Nairobi":  (0.18, 0.22),
    "Mombasa":  (0.10, 0.12),
    "Kisumu":   (0.08, 0.10),
    "Nakuru":   (0.12, 0.14),
    "Eldoret":  (0.10, 0.12),
}

DEFAULT_LAT_EXTENT = 0.08
DEFAULT_LNG_EXTENT = 0.10

# Generated files live in Towns/towns/ — one level below TownBase.py in
# Towns/ — so this needs TWO dots, not one. A single dot here is what
# caused every previously-generated file to be unimportable.
TEMPLATE = '''"""
{name}

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class {classname}(TownBase):
    def __init__(self):
        super().__init__(
            name="{name}",
            lat={lat},
            lng={lng},
            lat_extent={lat_extent},
            lng_extent={lng_extent},
            dataset_key={dataset},
            country_code="{country_code}",
        )
'''


def classname(name):
    return "".join(re.findall(r"[A-Za-z0-9]+", name.title()))


def filename(name):
    return classname(name) + ".py"


def lookup(name, country):
    url = "https://photon.komoot.io/api/"

    params = {
        "q": f"{name}, {country}",
        "limit": 1,
    }

    r = requests.get(
        url,
        params=params,
        headers={
            "User-Agent": "HiMap/1.0"
        },
        timeout=30,
    )

    r.raise_for_status()

    data = r.json()

    features = data.get("features", [])

    if not features:
        raise RuntimeError(f"Could not find {name}")

    coords = features[0]["geometry"]["coordinates"]

    lng = coords[0]
    lat = coords[1]

    return lat, lng

def write_town(outdir, name, lat, lng, dataset, cc):

    lat_extent, lng_extent = DEFAULT_EXTENTS.get(
        name,
        (DEFAULT_LAT_EXTENT, DEFAULT_LNG_EXTENT),
    )

    text = TEMPLATE.format(
        classname=classname(name),
        name=name,
        lat=round(lat, 6),
        lng=round(lng, 6),
        lat_extent=lat_extent,
        lng_extent=lng_extent,
        dataset=f'"{dataset}"' if dataset else "None",
        country_code=cc,
    )

    (outdir / filename(name)).write_text(text)


def main():

    parser = argparse.ArgumentParser()

    parser.add_argument("towns")
    parser.add_argument("output")

    parser.add_argument("--country", required=True)
    parser.add_argument("--dataset", default=None)
    parser.add_argument("--country-code", required=True)

    args = parser.parse_args()

    outdir = Path(args.output)
    outdir.mkdir(exist_ok=True)

    # Ensure the output directory is a proper package, not just a
    # namespace package — needed for the Registry auto-discovery to
    # import modules from it predictably.
    init_file = outdir / "__init__.py"
    if not init_file.exists():
        init_file.write_text('"""Auto-generated TownBase subclasses — see generate_towns.py."""\n')

    with open(args.towns) as f:

        towns = [
            line.strip()
            for line in f
            if line.strip()
        ]

    for town in towns:

        print(f"Looking up {town}...")

        try:
            lat, lng = lookup(town, args.country)

            print(f"  ({lat}, {lng})")

            write_town(
                outdir,
                town,
                lat,
                lng,
                args.dataset,
                args.country_code,
            )

        except Exception as e:
            print(f"FAILED: {town}: {e}")

        # Nominatim usage policy recommends no more than 1 request/sec
        time.sleep(1)


if __name__ == "__main__":
    main()
