"""
Town Registry — HiMap v3.0

Mirrors the DatasetRegistry pattern exactly.
Same register/get/list interface — callers work with both registries
the same way.

Town keys are lowercase, hyphenated:
    "nairobi", "las-palmas", "santa-cruz", "prague"

Linking towns to datasets:
    A town's dataset_key must match a key in the DatasetRegistry.
    The registry does NOT enforce this at register time (the dataset
    may be registered after the town), but to_bbox_params() and
    to_h3_params() will raise if dataset_key is unset.

Registration data lives elsewhere, not in this file:
    - Towns/Registry/curated_towns.py — hand-picked entries
    - Towns/Registry/auto_register.py — bulk-discovers Towns/towns/*.py
      (generated by generate_towns.py)
    Both are invoked from Towns/__init__.py at import time. This file
    is just the class and the singleton — same separation DataRegistry
    would benefit from too, but that's out of scope here.

Adding a new town:
    Prefer generate_towns.py + the Registry/auto_register.py discovery
    over calling town_registry.register() directly, unless the town
    needs hand-tuned extents or isn't in towns.txt — in which case add
    it to Towns/Registry/curated_towns.py instead.
"""

from typing import Dict, List, Optional
from .TownBase import TownBase


class TownRegistry:
    """
    Registry of all towns known to HiMap.
    Populated at startup. Read-only at query time.
    """

    def __init__(self) -> None:
        self._towns: Dict[str, TownBase] = {}

    def register(self, key: str, town: TownBase) -> None:
        """
        Register a town under the given key.

        Validates the town's spatial fields before accepting.
        Raises ValueError if key already registered.
        """
        if key in self._towns:
            raise ValueError(
                f"Town '{key}' already registered. "
                f"Call deregister() first if replacement is intentional."
            )
        town.validate()
        self._towns[key] = town

    def deregister(self, key: str) -> None:
        """Remove a town. Use in tests and migrations."""
        self._towns.pop(key, None)

    def get(self, key: str) -> TownBase:
        """
        Return town for a registered key.
        Raises ValueError (not KeyError) — callers convert to HTTP 400.
        """
        if key not in self._towns:
            raise ValueError(
                f"Unknown town: '{key}'. "
                f"Registered towns: {sorted(self._towns.keys())}"
            )
        return self._towns[key]

    def list(self) -> List[str]:
        """Sorted list of registered town keys."""
        return sorted(self._towns.keys())

    def list_by_dataset(self, dataset_key: str) -> List[str]:
        """Return all town keys linked to a given dataset."""
        return sorted(
            k for k, t in self._towns.items()
            if t.dataset_key == dataset_key
        )

    def all(self) -> Dict[str, TownBase]:
        """Shallow copy of the full registry."""
        return dict(self._towns)

    def __contains__(self, key: str) -> bool:
        return key in self._towns

    def __len__(self) -> int:
        return len(self._towns)


# ---------------------------------------------------------------------------
# Global registry instance
# Import this everywhere. Do not instantiate TownRegistry directly.
# Population happens in Towns/__init__.py (register_curated + register_generated),
# not here.
# ---------------------------------------------------------------------------

town_registry = TownRegistry()
