"""
Query Routes — HiMap v3.0

/query/all  — bounding box query
/query/h3   — H3 index query

SQL-agnostic contract:
    Routes never contain SQL strings.
    SQL is produced by ViewGenerator methods (bbox_query, h3_query).
    To change query logic: change ViewGenerator, not this file.

Data flow:
    Request params → validate dataset exists → get SQL from ViewGenerator
    → execute via DuckLakeService → serialize to FeaturesResponse
"""

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query

from ..Ingestion.DataRegistry import registry
from ..Services.DuckLakeService import ducklake_service
from ..Generator.viewGenerator import ViewGenerator
from ..Models.requests import BBoxQueryParams, H3QueryParams
from ..Models.responses import Feature, FeaturesResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/query", tags=["queries"])

# ViewGenerator is stateless — one instance is fine
view_generator = ViewGenerator(ducklake_service)


def _validate_dataset(dataset: str) -> None:
    """Raise HTTP 400 if dataset is not registered."""
    if dataset not in registry:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown dataset: '{dataset}'. Registered: {registry.list()}",
        )


def _rows_to_features(rows: list) -> list[Feature]:
    """
    Convert DuckDB result rows (dicts) to GeoJSON Feature objects.

    geometry is stored as WKB bytes — converted to GeoJSON point
    using stored centroid_lat/lng (avoids WKB parse on every row).
    """
    features = []
    for row in rows:
        # Use pre-computed centroid coords — no geometry parse needed
        geometry = {
            "type": "Point",
            "coordinates": [row.get("centroid_lng", 0), row.get("centroid_lat", 0)],
        }

        properties = {
            "feature_id":      row.get("feature_id"),
            "feature_type":    row.get("feature_type"),
            "country_code":    row.get("country_code"),
            "h3_7":            row.get("h3_7"),
            "h3_8":            row.get("h3_8"),
            "h3_9":            row.get("h3_9"),
            "h3_10":           row.get("h3_10"),
            "tile_z":          row.get("tile_z"),
            "tile_x":          row.get("tile_x"),
            "tile_y":          row.get("tile_y"),
            "entropy_score":   row.get("entropy_score"),
            "importance_byte": row.get("importance_byte"),
            "entropy_bucket":  row.get("entropy_bucket"),
            "highway":         row.get("highway"),
            "building":        row.get("building"),
            "amenity":         row.get("amenity"),
            "landuse":         row.get("landuse"),
            "road_class":      row.get("road_class"),
        }

        features.append(Feature(type="Feature", properties=properties, geometry=geometry))

    return features


# ---------------------------------------------------------------------------
# /query/all  — bounding box mode
# ---------------------------------------------------------------------------

@router.get(
    "/all",
    response_model=FeaturesResponse,
    summary="Bounding box query",
    responses={
        400: {"description": "Unknown dataset or invalid bbox"},
        500: {"description": "Query execution error"},
    },
)
async def query_bbox(
    dataset:  str           = Query(..., description="Registered dataset key"),
    sw_lng:   float         = Query(..., ge=-180, le=180),
    sw_lat:   float         = Query(..., ge=-90,  le=90),
    ne_lng:   float         = Query(..., ge=-180, le=180),
    ne_lat:   float         = Query(..., ge=-90,  le=90),
    zoom:     Optional[int] = Query(None, ge=0, le=20,
                                    description="Map zoom level. Scales feature limit and "
                                                "importance threshold automatically."),
    limit:    Optional[int] = Query(None, ge=1, le=10000,
                                    description="Override zoom-derived limit. "
                                                "Omit to use zoom-appropriate default."),
):
    """
    Return features within a bounding box for a registered dataset.

    Zoom-aware behaviour:
        zoom 0–9  (metro):         500 features, importance_byte >= 80 (landmarks only)
        zoom 10–12 (city):        2000 features, importance_byte >= 40
        zoom 13+  (neighborhood):  5000 features, all features returned

    Omitting zoom uses maximum limit with no importance filter.

    SQL is generated by ViewGenerator.bbox_query() — no SQL in this route.
    Results are ordered entropy_bucket ASC, importance_byte DESC —
    highest-value features arrive first for progressive rendering.
    """
    _validate_dataset(dataset)

    if sw_lng >= ne_lng or sw_lat >= ne_lat:
        raise HTTPException(status_code=400, detail="Invalid bounding box")

    width  = abs(ne_lng - sw_lng)
    height = abs(ne_lat - sw_lat)
    if width > 10 or height > 10:
        raise HTTPException(
            status_code=400,
            detail=f"Bounding box ({width:.2f}° × {height:.2f}°) exceeds 10° limit.",
        )

    try:
        from ..Utils.Zoom import zoom_levels as _zoom_levels

        sql  = view_generator.bbox_query(dataset, zoom=zoom)
        rows = ducklake_service.execute(sql, (sw_lng, sw_lat, ne_lng, ne_lat))

        # Apply caller override after query if supplied
        if limit and len(rows) > limit:
            rows = rows[:limit]

        features = _rows_to_features(rows)

        semantic = _zoom_levels.semantic_level(zoom) if zoom is not None else None

        return FeaturesResponse(
            dataset=dataset,
            count=len(features),
            features=features,
            query={
                "mode":                "bbox",
                "zoom":                zoom,
                "semantic":            semantic,
                "zoom_limit":          ViewGenerator._zoom_limit(zoom),
                "importance_threshold": ViewGenerator._importance_threshold(zoom),
                "sw_lng":              sw_lng,
                "sw_lat":              sw_lat,
                "ne_lng":              ne_lng,
                "ne_lat":              ne_lat,
                "limit_override":      limit,
            },
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"bbox query failed — dataset={dataset}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------------------------
# /query/h3  — H3 index mode
# ---------------------------------------------------------------------------

@router.get(
    "/h3",
    response_model=FeaturesResponse,
    summary="H3 index query",
    responses={
        400: {"description": "Unknown dataset or invalid resolution"},
        500: {"description": "Query execution error"},
    },
)
async def query_h3(
    dataset:    str          = Query(..., description="Registered dataset key"),
    h3_index:   str          = Query(..., description="H3 cell index (hex string)"),
    resolution: Optional[int] = Query(None, ge=7, le=10, description="H3 resolution (7–10). Overrides zoom if provided."),
    zoom:       Optional[int] = Query(None, ge=0, le=20,  description="Map zoom level — resolution is derived automatically."),
    limit:      int          = Query(5000, ge=1, le=10000),
):
    """
    Return features within an H3 cell for a registered dataset.

    Resolution priority:
        1. resolution param (explicit — use when you know the H3 resolution)
        2. zoom param (derived via ZoomLevel.h3_resolution_for_zoom)
        3. Default: resolution 8 (neighborhood scale)

    H3 queries are faster than bbox — preferred client path.
    SQL is generated by ViewGenerator — no SQL in this route.
    """
    _validate_dataset(dataset)

    # Resolve resolution from zoom if not explicitly provided
    if resolution is None:
        if zoom is not None:
            from ...Utils.Zoom import zoom_levels
            resolution = zoom_levels.h3_resolution_for_zoom(zoom)
        else:
            resolution = 8   # default: neighborhood scale

    try:
        sql = view_generator.h3_query(dataset, resolution, zoom=zoom)
        rows = ducklake_service.execute(sql, (h3_index,))

        # Apply caller override after query if supplied
        if limit and len(rows) > limit:
            rows = rows[:limit]

        features = _rows_to_features(rows)

        from ..Utils.Zoom import zoom_levels as _zoom_levels
        semantic = _zoom_levels.semantic_level(zoom) if zoom is not None else None

        return FeaturesResponse(
            dataset=dataset,
            count=len(features),
            features=features,
            query={
                "mode":                "h3",
                "h3_index":            h3_index,
                "resolution":          resolution,
                "zoom":                zoom,
                "semantic":            semantic,
                "zoom_limit":          ViewGenerator._zoom_limit(zoom),
                "importance_threshold": ViewGenerator._importance_threshold(zoom),
                "limit_override":      limit if limit else None,
            },
        )

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"H3 query failed — dataset={dataset} h3={h3_index}: {e}")
        raise HTTPException(status_code=500, detail=str(e))
