"""
Query Routes — HiMap v3.0

/query/all  — bounding box query
/query/h3   — H3 index query

SQL-agnostic contract:
    Routes never contain SQL strings.
    SQL is produced by ViewGenerator methods (bbox_query, h3_query).
    To change query logic: change ViewGenerator, not this file.

Data flow:
    Request params → validate dataset exists → get SQL from ViewGenerator
    → execute via DuckLakeService → serialize to FeaturesResponse
"""

import logging
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query

from ..Ingestion.DataRegistry import registry
from ..Services.DuckLakeService import ducklake_service
from ..Generator.viewGenerator import ViewGenerator
from ..Models.requests import BBoxQueryParams, H3QueryParams
from ..Models.responses import Feature, FeaturesResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/query", tags=["queries"])

# ViewGenerator is stateless — one instance is fine
view_generator = ViewGenerator(ducklake_service)


def _validate_dataset(dataset: str) -> None:
    """Raise HTTP 400 if dataset is not registered."""
    if dataset not in registry:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown dataset: '{dataset}'. Registered: {registry.list()}",
        )


def _rows_to_features(rows: list) -> list[Feature]:
    """
    Convert DuckDB result rows (dicts) to GeoJSON Feature objects.

    geometry is stored as WKB bytes — converted to GeoJSON point
    using stored centroid_lat/lng (avoids WKB parse on every row).
    """
    features = []
    for row in rows:
        # Use pre-computed centroid coords — no geometry parse needed
        geometry = {
            "type": "Point",
            "coordinates": [row.get("centroid_lng", 0), row.get("centroid_lat", 0)],
        }

        properties = {
            "feature_id":      row.get("feature_id"),
            "feature_type":    row.get("feature_type"),
            "country_code":    row.get("country_code"),
            "h3_7":            row.get("h3_7"),
            "h3_8":            row.get("h3_8"),
            "h3_9":            row.get("h3_9"),
            "h3_10":           row.get("h3_10"),
            "tile_z":          row.get("tile_z"),
            "tile_x":          row.get("tile_x"),
            "tile_y":          row.get("tile_y"),
            "entropy_score":   row.get("entropy_score"),
            "importance_byte": row.get("importance_byte"),
            "entropy_bucket":  row.get("entropy_bucket"),
            "highway":         row.get("highway"),
            "building":        row.get("building"),
            "amenity":         row.get("amenity"),
            "landuse":         row.get("landuse"),
            "road_class":      row.get("road_class"),
        }

        features.append(Feature(type="Feature", properties=properties, geometry=geometry))

    return features


# ---------------------------------------------------------------------------
# /query/all  — bounding box mode
# ---------------------------------------------------------------------------

@router.get(
    "/all",
    response_model=FeaturesResponse,
    summary="Bounding box query",
    responses={
        400: {"description": "Unknown dataset or invalid bbox"},
        500: {"description": "Query execution error"},
    },
)
async def query_bbox(
    dataset:  str   = Query(..., description="Registered dataset key"),
    sw_lng:   float = Query(..., ge=-180, le=180),
    sw_lat:   float = Query(..., ge=-90,  le=90),
    ne_lng:   float = Query(..., ge=-180, le=180),
    ne_lat:   float = Query(..., ge=-90,  le=90),
    limit:    int   = Query(5000, ge=1, le=10000),
):
    """
    Return features within a bounding box for a registered dataset.

    SQL is generated by ViewGenerator.bbox_query() — no SQL in this route.
    Results are ordered by entropy_bucket ASC, importance_byte DESC
    (highest-value features first, matching the VoI priority contract).
    """
    _validate_dataset(dataset)

    if sw_lng >= ne_lng or sw_lat >= ne_lat:
        raise HTTPException(status_code=400, detail="Invalid bounding box")

    try:
        # Get parameterized SQL from ViewGenerator — no SQL here
        sql = view_generator.bbox_query(dataset)
        rows = ducklake_service.execute(sql, (sw_lng, sw_lat, ne_lng, ne_lat))

        if limit and len(rows) > limit:
            rows = rows[:limit]

        features = _rows_to_features(rows)

        return FeaturesResponse(
            dataset=dataset,
            count=len(features),
            features=features,
            query={
                "mode":   "bbox",
                "sw_lng": sw_lng,
                "sw_lat": sw_lat,
                "ne_lng": ne_lng,
                "ne_lat": ne_lat,
                "limit":  limit,
            },
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"bbox query failed — dataset={dataset}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------------------------
# /query/h3  — H3 index mode
# ---------------------------------------------------------------------------

@router.get(
    "/h3",
    response_model=FeaturesResponse,
    summary="H3 index query",
    responses={
        400: {"description": "Unknown dataset or invalid resolution"},
        500: {"description": "Query execution error"},
    },
)
async def query_h3(
    dataset:    str = Query(..., description="Registered dataset key"),
    h3_index:   str = Query(..., description="H3 cell index (hex string)"),
    resolution: int = Query(8, ge=7, le=10, description="H3 resolution (7–10)"),
    limit:      int = Query(5000, ge=1, le=10000),
):
    """
    Return features within an H3 cell for a registered dataset.

    SQL is generated by ViewGenerator.h3_query() — no SQL in this route.
    H3 queries are faster than bbox — preferred path for client prefetch.
    """
    _validate_dataset(dataset)

    try:
        # Get parameterized SQL from ViewGenerator — no SQL here
        sql = view_generator.h3_query(dataset, resolution)
        rows = ducklake_service.execute(sql, (h3_index,))

        if limit and len(rows) > limit:
            rows = rows[:limit]

        features = _rows_to_features(rows)

        return FeaturesResponse(
            dataset=dataset,
            count=len(features),
            features=features,
            query={
                "mode":       "h3",
                "h3_index":   h3_index,
                "resolution": resolution,
                "limit":      limit,
            },
        )

    except ValueError as e:
        # ViewGenerator raises ValueError for invalid resolution
        raise HTTPException(status_code=400, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"H3 query failed — dataset={dataset} h3={h3_index}: {e}")
        raise HTTPException(status_code=500, detail=str(e))
