"""
Bomet

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Bomet(TownBase):
    def __init__(self):
        super().__init__(
            name="Bomet",
            lat=-0.719605,
            lng=35.239962,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
