"""
Bungoma

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Bungoma(TownBase):
    def __init__(self):
        super().__init__(
            name="Bungoma",
            lat=0.782925,
            lng=34.719168,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
