"""
Busia

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Busia(TownBase):
    def __init__(self):
        super().__init__(
            name="Busia",
            lat=0.371205,
            lng=34.264795,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
