"""
Eldoret

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Eldoret(TownBase):
    def __init__(self):
        super().__init__(
            name="Eldoret",
            lat=0.519833,
            lng=35.271548,
            lat_extent=0.1,
            lng_extent=0.12,
            dataset_key="kenya",
            country_code="KE",
        )
