"""
Embu

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Embu(TownBase):
    def __init__(self):
        super().__init__(
            name="Embu",
            lat=-0.535948,
            lng=37.665288,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
