"""
Garissa

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Garissa(TownBase):
    def __init__(self):
        super().__init__(
            name="Garissa",
            lat=-0.523633,
            lng=40.356405,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
