"""
Hola

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Hola(TownBase):
    def __init__(self):
        super().__init__(
            name="Hola",
            lat=-1.497681,
            lng=40.034911,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
