"""
Homa Bay

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class HomaBay(TownBase):
    def __init__(self):
        super().__init__(
            name="Homa Bay",
            lat=-0.56396,
            lng=34.318782,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
