"""
Isiolo

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Isiolo(TownBase):
    def __init__(self):
        super().__init__(
            name="Isiolo",
            lat=1.00606,
            lng=38.747895,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
