"""
Iten

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Iten(TownBase):
    def __init__(self):
        super().__init__(
            name="Iten",
            lat=0.67307,
            lng=35.510263,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
