"""
Kabarnet

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kabarnet(TownBase):
    def __init__(self):
        super().__init__(
            name="Kabarnet",
            lat=0.496524,
            lng=35.743139,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
