"""
Kajiado

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kajiado(TownBase):
    def __init__(self):
        super().__init__(
            name="Kajiado",
            lat=-2.121717,
            lng=36.786255,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
