"""
Kakamega

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kakamega(TownBase):
    def __init__(self):
        super().__init__(
            name="Kakamega",
            lat=0.49571,
            lng=34.801549,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
