"""
Kapenguria

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kapenguria(TownBase):
    def __init__(self):
        super().__init__(
            name="Kapenguria",
            lat=1.252252,
            lng=35.090992,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
