"""
Kapsabet

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kapsabet(TownBase):
    def __init__(self):
        super().__init__(
            name="Kapsabet",
            lat=0.200498,
            lng=35.10115,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
