"""
Kericho

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kericho(TownBase):
    def __init__(self):
        super().__init__(
            name="Kericho",
            lat=-0.320997,
            lng=35.226128,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
