"""
Kiambu

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kiambu(TownBase):
    def __init__(self):
        super().__init__(
            name="Kiambu",
            lat=-1.036395,
            lng=36.843131,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
