"""
Kilifi

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kilifi(TownBase):
    def __init__(self):
        super().__init__(
            name="Kilifi",
            lat=-3.150739,
            lng=39.675072,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
