"""
Kisii

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kisii(TownBase):
    def __init__(self):
        super().__init__(
            name="Kisii",
            lat=-0.738942,
            lng=34.753985,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
