"""
Kisumu

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kisumu(TownBase):
    def __init__(self):
        super().__init__(
            name="Kisumu",
            lat=-0.108233,
            lng=34.751699,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
