"""
Kitale

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kitale(TownBase):
    def __init__(self):
        super().__init__(
            name="Kitale",
            lat=1.018076,
            lng=35.000236,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
