"""
Kitui

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kitui(TownBase):
    def __init__(self):
        super().__init__(
            name="Kitui",
            lat=-1.564222,
            lng=38.372812,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
