"""
Kwale

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Kwale(TownBase):
    def __init__(self):
        super().__init__(
            name="Kwale",
            lat=-4.183607,
            lng=39.105095,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
