"""
Lamu

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Lamu(TownBase):
    def __init__(self):
        super().__init__(
            name="Lamu",
            lat=-2.267496,
            lng=40.901038,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
