"""
Lodwar

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Lodwar(TownBase):
    def __init__(self):
        super().__init__(
            name="Lodwar",
            lat=3.116586,
            lng=35.602294,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
