"""
Machakos

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Machakos(TownBase):
    def __init__(self):
        super().__init__(
            name="Machakos",
            lat=-1.279005,
            lng=37.39527,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
