"""
Malindi

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Malindi(TownBase):
    def __init__(self):
        super().__init__(
            name="Malindi",
            lat=-3.220861,
            lng=40.10005,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
