"""
Mandera

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Mandera(TownBase):
    def __init__(self):
        super().__init__(
            name="Mandera",
            lat=3.228533,
            lng=40.705615,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
