"""
Maralal

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Maralal(TownBase):
    def __init__(self):
        super().__init__(
            name="Maralal",
            lat=1.1,
            lng=36.7,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
