"""
Marsabit

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Marsabit(TownBase):
    def __init__(self):
        super().__init__(
            name="Marsabit",
            lat=2.857958,
            lng=37.715489,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
