"""
Mbale

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Mbale(TownBase):
    def __init__(self):
        super().__init__(
            name="Mbale",
            lat=0.083501,
            lng=34.720326,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
