"""
Meru

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Meru(TownBase):
    def __init__(self):
        super().__init__(
            name="Meru",
            lat=0.225451,
            lng=37.777262,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
