"""
Migori

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Migori(TownBase):
    def __init__(self):
        super().__init__(
            name="Migori",
            lat=-1.019224,
            lng=34.309543,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
