"""
Mombasa

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Mombasa(TownBase):
    def __init__(self):
        super().__init__(
            name="Mombasa",
            lat=-4.05052,
            lng=39.667169,
            lat_extent=0.1,
            lng_extent=0.12,
            dataset_key="kenya",
            country_code="KE",
        )
