"""
Murang'a

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class MurangA(TownBase):
    def __init__(self):
        super().__init__(
            name="Murang'a",
            lat=-0.723656,
            lng=37.157586,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
