"""
Nairobi

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Nairobi(TownBase):
    def __init__(self):
        super().__init__(
            name="Nairobi",
            lat=-1.302398,
            lng=36.828851,
            lat_extent=0.18,
            lng_extent=0.22,
            dataset_key="kenya",
            country_code="KE",
        )
