"""
Naivasha

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Naivasha(TownBase):
    def __init__(self):
        super().__init__(
            name="Naivasha",
            lat=-0.722442,
            lng=36.438783,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
