"""
Nakuru

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Nakuru(TownBase):
    def __init__(self):
        super().__init__(
            name="Nakuru",
            lat=-0.280272,
            lng=36.071205,
            lat_extent=0.12,
            lng_extent=0.14,
            dataset_key="kenya",
            country_code="KE",
        )
