"""
Nanyuki

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Nanyuki(TownBase):
    def __init__(self):
        super().__init__(
            name="Nanyuki",
            lat=0.01403,
            lng=37.074632,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
