"""
Narok

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Narok(TownBase):
    def __init__(self):
        super().__init__(
            name="Narok",
            lat=-1.277937,
            lng=35.477423,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
