"""
Nyamira

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Nyamira(TownBase):
    def __init__(self):
        super().__init__(
            name="Nyamira",
            lat=-0.651791,
            lng=34.934167,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
