"""
Nyeri

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Nyeri(TownBase):
    def __init__(self):
        super().__init__(
            name="Nyeri",
            lat=-0.419296,
            lng=36.951701,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
