"""
Ol Kalou

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class OlKalou(TownBase):
    def __init__(self):
        super().__init__(
            name="Ol Kalou",
            lat=-0.289173,
            lng=36.314787,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
