"""
Siaya

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Siaya(TownBase):
    def __init__(self):
        super().__init__(
            name="Siaya",
            lat=-0.060401,
            lng=34.200135,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
