"""
Thika

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Thika(TownBase):
    def __init__(self):
        super().__init__(
            name="Thika",
            lat=-1.180695,
            lng=36.930847,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
