"""
Wajir

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Wajir(TownBase):
    def __init__(self):
        super().__init__(
            name="Wajir",
            lat=1.93944,
            lng=40.024736,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
