"""
Wote

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Wote(TownBase):
    def __init__(self):
        super().__init__(
            name="Wote",
            lat=-1.780317,
            lng=37.629035,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
