"""
Wundanyi

Auto-generated by generate_towns.py
"""

from ..TownBase import TownBase


class Wundanyi(TownBase):
    def __init__(self):
        super().__init__(
            name="Wundanyi",
            lat=-3.064856,
            lng=38.180552,
            lat_extent=0.08,
            lng_extent=0.1,
            dataset_key="kenya",
            country_code="KE",
        )
