"""
Registry package — HiMap v3.0

Top-level (sibling of Towns/, Ingestion/, etc.) — deliberately not
nested inside any one domain, since DataRegistry and BuildingRegistry's
registration data could move here too eventually. For now it holds
Towns' registration sources:

    1. curated_towns.py  — hand-picked/hand-tuned entries (Nairobi with
       custom extents, Las Palmas, Santa Cruz, Prague). Register first,
       win any key collision.

    2. auto_registry.py  — bulk-discovers everything under
       Towns/towns/ (generated by generate_towns.py). Registers second;
       skips any key a curated entry already claimed (nairobi/mombasa/
       kisumu collide by design — DEFAULT_EXTENTS in generate_towns.py
       matches the curated values for those three).

Usage (this is what Towns/__init__.py does — you shouldn't normally
need to call these yourself):

    from himap.Towns.TownRegistry import town_registry
    from himap.Registry import register_curated, register_generated

    register_curated(town_registry)
    register_generated(town_registry)
"""

from .curated_towns import register_curated
from .auto_registry import register_generated, discover_towns

__all__ = ["register_curated", "register_generated", "discover_towns"]
